models:
  - name: AutoNHITS
    active: true
    params:
      h: [24, 48]
      input_size: [48, 72]
      batch_size: {type: int, min: 32, max: 128, step: 32}
  - name: AutoTFT
    active: true
    params:
      h: [24]
      input_size: [72]
      batch_size: [32, 64]
