name: dq-smoke
on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
  workflow_dispatch: {}
jobs:
  dq:
    if: contains(github.event.pull_request.labels.*.name, 'dq-gate') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install dq deps (editable ok)
        run: |
          python -m pip install -U pip
          pip install -e .[dq]
      - name: Prepare sample data & schema (safe default)
        run: |
          mkdir -p data schema
          printf 'unique_id,ds,y\nA,2025-01-01,1.0\nA,2025-01-02,2.0\n' > data/sample.csv
          cat > schema/schema.json <<'JSON'
          {"columns":{"unique_id":{"type":"string"},
                      "ds":{"type":"datetime","tz":"Asia/Tokyo","freq":"D"},
                      "y":{"type":"number"}}}
          JSON
      - name: Run dq smoke
        run: |
          python -m phase2.dq_runner --input data/sample.csv --schema schema/schema.json --chunksize 200000 || true
