name: dq
on:
  pull_request:
    types: [opened, synchronize, labeled]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -U pip && pip install -e .[dev]
      - run: command -v dq >/dev/null && dq --help || { echo "dq not found in PATH"; exit 1; }
      - run: echo "DQ Smoke OK"  # 常に成功
  gate:
    if: contains(github.event.pull_request.labels.*.name, 'dq-gate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -U pip && pip install -e .[dev]
      - run: dq --version || true
      - run: |
          dq --input data/sample.parquet --schema schema/schema.json \
             --chunksize 50000 --invalid-cap 10000 --invalid-rate-threshold 0.02
