name: gate
on:
  pull_request:
  workflow_dispatch: {}
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick checks
        run: |
          git --version
          python3 -V
          echo "Gate OK"
