name: pytest-heavy
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 19 * * *'   # UTC（毎日19:30）
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  heavy:
    # PR時は heavy ラベルが付いているときのみ実行
    if: >
      github.event_name != 'pull_request'
      || contains(github.event.pull_request.labels.*.name, 'heavy')
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
            requirements-dev.txt

      - name: Install (dev heavy)
        run: |
          set -euxo pipefail
          python -m pip install -U pip
          pip install -e .[dev] pytest pytest-xdist "scipy>=1.11"

      - name: PyTest (heavy/slow)
        run: |
          pytest -o addopts= -p xdist.plugin -vv \
                 -m "heavy or slow" \
                 -n auto --dist loadfile --durations=20 \
                 --maxfail=1

      - name: Upload junit report (optional if you have one)
        if: always() && hashFiles('pytest-report.xml') != ''
        uses: actions/upload-artifact@v4
        with:
          name: junit-heavy
          path: pytest-report.xml
          if-no-files-found: ignore
