name: pytest
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"   # 余計な外部pytestプラグインの自動読込を禁止して起動高速化
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
            requirements-dev.txt
      - name: Install (dev)
        run: |
          python -m pip install -U pip
          pip install -e .[dev] pytest pytest-xdist "scipy>=1.11"
      - name: Collect pip verbose logs
        run: bash tools/pip-logs-collect.sh || true
      - name: PyTest (light & fast)
        run: |
          pytest -q -m "not heavy" -k "not phase5 and not phase6 and not phase11 and not slow" \
                 -n auto --dist loadfile --durations=10
      - name: Report pip cache hit rate
        run: |
          bash tools/pip-cache-hit-rate.sh pip-logs/pip_install_verbose.log
          echo '### pip cache hit' >> $GITHUB_STEP_SUMMARY
          cat pip-logs/cache_hit_rate.txt >> $GITHUB_STEP_SUMMARY
      - name: Upload pip logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pip-logs-pytest
          path: pip-logs/**
          if-no-files-found: ignore
