name: pytest
on:
  push:
  pull_request:
  workflow_dispatch: {}
concurrency:
  # 手動発火と自動発火を分離（相互に cancel しない）
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
            requirements-dev.txt

      - name: Install (dev)
        run: |
          set -euxo pipefail
          python -m pip install -U pip
          pip install -e .[dev] pytest pytest-xdist "scipy>=1.11"

      - name: Collect pip verbose logs
        run: bash tools/pip-logs-collect.sh || true

      - name: Ensure pip log exists
        run: |
          mkdir -p pip-logs
          # 空でもよいので必ずこのファイル名を用意（後続で参照）
          : > pip-logs/pip_install_verbose.log

      # 収集前クラッシュの可視化（ImportError などを確実に出す）
      - name: PyTest collect-only (debug)
        continue-on-error: true
        run: |
          pytest --collect-only -vv \
                 -m "not heavy" \
                 -k "not phase5 and not phase6 and not phase11 and not slow"

      - name: PyTest (light & fast)
        run: |
          pytest -vv \
                 -m "not heavy" \
                 -k "not phase5 and not phase6 and not phase11 and not slow" \
                 -n auto --dist loadfile --durations=10

      - name: Report pip cache hit rate
        if: always()
        run: |
          set -euxo pipefail
          if [ -s pip-logs/pip_install_verbose.log ]; then
            bash tools/pip-cache-hit-rate.sh pip-logs/pip_install_verbose.log || true
            echo '### pip cache hit' >> "$GITHUB_STEP_SUMMARY"
            cat pip-logs/cache_hit_rate.txt >> "$GITHUB_STEP_SUMMARY" 2>/dev/null || true
          else
            echo '### pip cache hit' >> "$GITHUB_STEP_SUMMARY"
            echo 'no pip_install_verbose.log (early failure)' >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload pip logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pip-logs-pytest
          path: pip-logs/**
          if-no-files-found: warn
