name: pytest
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11', cache: 'pip'}
      - name: Install (dev)
        run: |
          python -m pip install -U pip
          pip install -e .[dev] pytest
          pip install "scipy>=1.11"
      - name: PyTest (light)
      - name: Upload pip logs
        uses: actions/upload-artifact@v4
        with:
          name: pip-logs-$(date +%s)
          path: pip-logs/**
          if-no-files-found: ignore
        run: pytest -q -m "not heavy"
